class data():
    meal = [
        {
            'meal_id': 1,
            'name': 'Cơm bò kiểu Hàn Quốc với dưa chuột',
            'source': 'icons_and_images/Korean-Style Beef Rice Bowl with Cucumbers.png',
            'cookware': 'dao;chao;thớt;máy ép tỏi(tùy chọn);bàn mài(tùy chọn);muỗng đong;âu trộn bột;chảo chống dính;chảo nhỏ;thìa khuấy;đồ đánh trứng hoặc nĩa',
            'ingredients': '2 dưa chuột Anh;2 tép tỏi;2(2,5cm) miếng gừng củ; 1 bó nhỏ hành lá; 1 chén cơm jasmine;680 gram thịt bò nạc xay; nước sốt ớt tỏi; ớt đỏ nghiền nát;mật ong;gạo giấm; nước tương; dầu mè;',
            'cook': '1.Dùng rây lọc hoặc chao, vo gạo dưới vòi nước lạnh, sau đó để ráo và chuyển sang một cái chảo nhỏ. Thêm nước vào xoong. Đun sôi hỗn hợp trên lửa lớn.(1 chén cơm jasmine,2 cốc nước);2.Rửa và làm khô các sản phẩm tươi.(2 dưa chuột Anh, 2 (2,5cm) củ gừng,1 bó nhỏ hành lá);3.Trong một bát salad lớn, kết hợp và đánh đều giấm gạo, mật ong và ớt đỏ nghiền nhỏ.(2 muỗng canh, giấm gạo,2 muỗng cà phê mật ong,¼ muỗng cà phê ớt đỏ nghiền);4.Khi chất lỏng sôi, khuấy đều hỗn hợp, đậy vung và giảm lửa nhỏ. Nấu cơm cho đến khi chất lỏng ngấm hoàn toàn, từ 15 đến 18 phút. Sau khi hoàn thành, lấy cơm ra khỏi bếp và để yên trong 5 phút.;5.Cắt bỏ phần đầu của dưa chuột, xắt dưa chuột theo chiều ngang thành những miếng tròn thật mỏng. Thêm vào bát salad.;6.Gọt vỏ và cạo hoặc băm nhuyễn gừng. Chuyển sang một cái bát nhỏ.;7.Cắt bỏ phần đầu củ của tỏi, bóc vỏ và băm hoặc ép tỏi. Cho gừng vào bát.(2 tép tỏi);8.Đối với gừng và tỏi, thêm nước tương, dầu mè và mật ong.(4 muỗng canh nước tương,1 muỗng cà phê ,dầu mè,2 muỗng cà phê mật ong);9. Làm nóng chảo chống dính trên lửa với nhiệt độ vừa.;10. Cắt bỏ đầu hành lá,cắt hành tây theo chiều ngang thành các miếng(0,6cm) ở một góc. Chuyển sang một cái bát nhỏ.;11. Khi chảo nóng, cho thịt bò xay vào chảo nấu, dùng thìa bẻ đôi cho đến khi chín vàng và vụn, từ 3 đến 4 phút.(680 lb thịt bò nạc xay);12. Cho hỗn hợp nước tương và khoảng ¾ số hành lá (phần còn lại để trang trí) vào thịt bò khuấy để kết hợp và nấu thêm 1 đến 2 phút.;13. Dùng nĩa để lật cơm.;14. Để phục vụ, chia cơm, thịt bò và dưa chuột giữa các đĩa. Trang trí với phần hành lá còn lại và nước mắm tỏi ớt. Tận hưởng nào!( 2 muỗng cà phê nước sốt ớt tỏi);'
        },
        {
            'meal_id': 2,
            'name': 'Gà quay Peru cay & Rau với ngò-Feta Salsa',
            'source': 'icons_and_images/Spicy Peruvian Roast Chicken & Veggies with Cilantro-Feta Salsa.png',
            'cookware': 'chảo nướng;dao;máy ép trái cây; chao;thớt;máy ép tỏi(tùy chọn);bàn mài(tùy chọn);muỗng đong;âu trộn bột;gang tay chống nóng;dao bay;chảo thép không ghỉ hoặc gang;thìa khuấy;kẹp;máy gọt rau củ',
            'ingredients': '2 củ cà rốt vừa;1kg đùi gà rút xương, không da;2 chùm nhỏ ngò;100g pho mát feta vụn;4 tép tỏi;2 trái ớt jalapeno;2 quả chanh;1 ớt chuông cam;2 trái bí ngòi vừa; tiêu đen; ớt cayenne;thì là,đất; dầu ô liu nguyên chất;lá oregano, khô;muối;',
            'cook': '1.Làm nóng lò ở 218 ° C. Đặt giá đỡ ở phần ba trên và dưới của lò.;2.Rửa và làm khô các sản phẩm tươi.(2 củ cà rốt vừa,1 quả ớt chuông cam,2 bí xanh vừa,2 quả chanh,2 quả ớt jalapeño,2 bó nhỏ ngò);3.Gọt vỏ và cắt cà rốt thành những miếng tròn dày 1,3cm. Ớt chuông bỏ hạt và thái hạt lựu lớn. Chuyển cả hai vào một tô lớn.;4.Cắt đôi quả bí xanh theo chiều dọc, sau đó cắt lát chéo thành các nửa tròn dày 1,3cm. Cho vào bát, rưới dầu, nêm muối tiêu.(4 muỗng cà phê dầu ô liu nguyên chất,¼ muỗng cà phê muối,¼ muỗng cà phê tiêu đen);5.Xếp rau trên một khay nướng lớn thành một lớp. Đặt trên giá dưới của lò và nướng, lật giữa chừng, cho đến khi nĩa chín mềm, trong vòng 20-25 phút.;6.Trong khi đó, hãy lấy vỏ và vắt chanh vào bát dùng để đựng rau. Để phần vôi còn lại sang một bên.;7.Bóc vỏ và băm nhuyễn tỏi. Thêm vào bát cùng với dầu và gia vị. Khuấy đều để kết hợp hỗn hợp gia vị.(2 tép tỏi,2 muỗng cà phê dầu ô liu nguyên chất,1 ½ thìa cà phê thìa là,½ muỗng trà oregano,½ muỗng cà phê ớt cayenne,½ muỗng cà phê muối);8.Làm nóng trước một chảo lớn cách nhiệt bằng lò nướng ở nhiệt độ trung bình và cao.;9.Trong khi chảo nóng lên, dùng khăn giấy thấm khô đùi gà và cho vào bát cùng với hỗn hợp gia vị.(Đùi gà 57gram, không da);10.Sau khi chảo nóng, thêm dầu và xoáy để tráng phần đáy. Cho thịt gà vào từng lớp, và nấu ở một mặt cho đến khi vàng nâu và có màu caramel, khoảng 5 phút. Lật và nấu thêm 1 phút, sau đó lấy ra khỏi bếp (gà sẽ không chín hoàn toàn).(4 muỗng cà phê dầu ô liu nguyên chất);11.Chuyển chảo lên giá trên của lò nướng và nướng cho đến khi gà chín trong vòng 12-15 phút.;12.Trong khi đó, nước cốt chanh còn lại vào một cái bát vừa.;13.Ớt jalapeño quý theo chiều dọc, hạt và loại bỏ xương sườn bằng thìa. Băm nhuyễn và cho vào bát cùng với nước cốt chanh. (Hãy cẩn thận, với jalapeños, không chạm vào mắt và đảm bảo bạn rửa tay sau khi xử lý hoặc đeo găng tay trong khi chuẩn bị.);14.Ngò rí cạo bỏ cọng, Loại bỏ thân và băm nhỏ lá. Thêm vào bát.;15.Bóc vỏ và băm nhuyễn tỏi. Thêm vào bát cùng với Feta, dầu, thìa là và muối. Khuấy đều để kết hợp salsa.(2 tép tỏi,1 (4 oz) pkg pho mát Feta vụn,4 muỗng cà phê dầu ô liu nguyên chất,1 thìa cà phê thìa là,¼ muỗng cà phê muối);16.Để phục vụ, chia rau và thịt gà giữa các đĩa. Múc salsa lên thịt gà và thưởng thức!'
        },
        {
            'meal_id': 3,
            'name': 'Cá hồi tẩm gia vị Mexico với Óc chó Guacamole & Ớt chuông-Xào ngô',
            'source': 'icons_and_images/Mexican Spiced Salmon with Walnut Guacamole & Bell Pepper-Corn Saute.png',
            'cookware': 'Chảo nướng;dao;máy ép trái cây;chao;thớt;máy ép tỏi(tùy chọn);ly đo lường;muỗng đong;âu trộn bột;chảo chống dính;găng chống nóng; máy nghiền khoai tây;dao bay;thìa khuấy',
            'ingredients': '2 bơ;1 bó nhỏ ngò;2 tách Ngô đông lạnh;2 tép tỏi;2 Chanh;4 ớt chuông đỏ;0,68 kg cá hồi phi lê;1 củ hẹ;¼ cốc Quả óc chó;tiêu đen;bột ớt;thì là;dầu ô liu nguyên chất;oregano, khô;Muối;',
            'cook': '1.Làm nóng lò nướng để nướng thịt trên cao và đặt giá dưới lò nướng.2.Rửa và làm khô các sản phẩm tươi.(4 quả ớt chuông đỏ,1 bó nhỏ ngò,2 quả chanh,2 quả bơ);3.Ớt chuông cắt hạt lựu, cắt hạt lựu nhỏ, đặt trong một cái bát vừa.;4.Ngò rí cạo bỏ cọng, Loại bỏ thân và băm nhỏ lá. Cho ớt chuông vào tô và để riêng.;5.Dùng khăn giấy thấm khô cá và chuyển sang khay nướng. Rưới dầu đều hai mặt, xếp mặt da xuống, sau đó nêm gia vị lên mặt trên.(0,68 kg phi lê cá hồi,4 muỗng cà phê dầu ô liu nguyên chất,1 muỗng cà phê ớt bột,1 muỗng cà phê oregano, khô,1 muỗng cà phê muối,½ muỗng cà phê tiêu đen,½ thìa cà phê thì là xay);6.Đặt khay nướng vào lò nướng và nướng cho đến khi cá hồi chỉ còn màu đục, khoảng 5 phút. Lật cá hồi và tiếp tục nướng cho đến khi da giòn, thêm 3-4 phút. Lấy ra khỏi lò.;7.Trong khi đó, làm nóng chảo lớn trên lửa vừa.;8.Sau khi chảo nóng, thêm dầu và xoáy để tráng phần đáy. Thêm ớt chuông, ngò, ngô, muối và tiêu, nấu, thỉnh thoảng khuấy cho đến khi rau chín mềm, khoảng 5 phút. Loại bỏ khỏi nhiệt. (Dự trữ bát cho bước tiếp theo.)(4 muỗng cà phê dầu ô liu nguyên chất,2 cốc ngô đông lạnh,1 muỗng cà phê muối,¼ muỗng cà phê tiêu đen);9.Trong khi rau nấu chín, bóc vỏ và băm nhuyễn hành tím và tỏi. Đặt cả hai vào bát đã đặt trước.(1 củ hẹ,2 tép tỏi);10.Cho một quả chanh vào bát cùng với hành tím và tỏi. (Cắt phần chanh còn lại thành các miếng nêm và để riêng cho bữa ăn.);11.Giảm nửa quả bơ, dùng thìa xúc phần thịt cho vào bát. Thêm gia vị và nghiền bằng nĩa hoặc dụng cụ nghiền khoai tây cho đến khi guacamole mịn.(¼ muỗng cà phê muối,¼ muỗng cà phê tiêu đen,¼ muỗng trà ớt bột);12.Băm nhỏ quả óc chó, cho vào bát cùng với guacamole và khuấy đều để kết hợp.(¼ tách quả óc chó);13.Chia cá hồi và rau giữa các đĩa, đầu cá hồi với guacamole và phục vụ với chanh để vắt. Tận hưởng món ăn!;'
        },
        {
            'meal_id': 4,
            'name': 'Bánh Quesadillas Đậu Đen & Rau Với Cà Chua & Bơ Salsa',
            'source': 'icons_and_images/Black Bean & Veggie Quesadillas with Tomato & Avocado Salsa.png',
            'cookware': 'Dụng cụ mở hộp;Dao bếp;Cái rỗ trút nước;Cái thớt;Đồ nạo;Một vài chiếc ly đo dung tích;Muỗng đo dung tích;Tô để trộn thức ăn;Máy trộn salad(tự chọn);Chảo chống dính',
            'ingredients': '2 trái bơ;398 ml đậu đen;227g phô mai cheddar;1 bó rau mùi;2 trái Ớt Jalapeño;4 bánh tortillas lớn;1 quả chanh ;2 trái ớt chuông;1 trái hành đỏ(cỡ vừa) ;4 trái cà chua;tiêu đen;ớt bột;thì là;dầu ô liu;muối;',
            'cook': '1.Rửa và lau khô cà chua, ớt sừng và ngò(4 quả cà chua,2 quả ớt jalapeño,1 bó nhỏ ngò);2.Chuyển cà chua đã cắt sang một bát vừa. Bỏ hạt, băm nhuyễn và thêm ½ số jalapeños vào bát (để dành phần còn lại cho phần nhân quesadilla). Một nửa quả bơ và quả bơ, múc phần thịt, thái hạt lựu vừa phải, cho vào bát. Ngò rí cạo bỏ cọng, Loại bỏ phần thân, băm nhỏ phần lá và cho ½ vào bát (để dành phần còn lại cho phần nhân quesadilla). Bóc vỏ, thái hạt lựu nhỏ hành tây và cho ½ vào bát (để dành phần còn lại làm nhân quesadilla).(1 củ hành tím vừa);3.Đổ nguyên liệu vào bát với dầu ô liu và nước cốt chanh, Nêm với muối và hạt tiêu. Trộn để kết hợp và để sang một bên.(2 muỗng cà phê dầu ô liu nguyên chất,nước cốt của 1 quả chanh,500g muỗng cà phê muối,250g muỗng cà phê tiêu đen);4.Đun chảo trên lửa vừa.;5.Ớt chuông rửa sạch, bỏ hạt, thái hạt lựu nhỏ.(2 quả ớt chuông đỏ);6.Phủ dầu lên đáy chảo. Thêm hành tây, ớt chuông và ớt chuông còn lại. Khuấy thường xuyên, nấu cho đến khi rau mềm, 3-4 phút.(2 muỗng canh dầu ô liu nguyên chất);7.Để ráo và rửa sạch đậu.(398 ml lon đậu đen);8.Thêm đậu và rau mùi còn lại vào chảo. Sau đó nêm ớt bột, thìa là, muối, tiêu. Khuấy và nấu cho đến khi đậu ấm qua 2-3 phút. Chuyển sang tô.(1 muỗng cà phê ớt bột,1 thìa cà phê thìa là,500g muỗng cà phê muối,250g muỗng cà phê tiêu đen);9.Bào 2 cốc cheddar.(227 g phô mai cheddar khối);10.Rửa và làm khô chảo. Đun lửa vừa.;11.Đặt bánh trên một bề mặt phẳng. Lớp một nửa của mỗi bánh tortilla với ⅛ pho mát, ¼ hỗn hợp đậu và ⅛ pho mát khác. Gấp bánh ngô lại để đóng.(4 bánh bột mì lớn (cỡ burrito));12.Bôi chảo bằng dầu. Đặt 2 trong số các quesadillas vào chảo, các cạnh thẳng cạnh nhau. Nấu cho đến khi vàng nâu cả hai mặt và phô mai chảy ra, 2-3 phút mỗi mặt. Lặp lại với 2 quesadillas còn lại.(1 muỗng canh dầu ô liu nguyên chất);13.Chuyển sang thớt và cắt thành hình nêm.;14.Để phục vụ, đặt quesadilla ra đĩa và dùng kèm với salsa. Tận hưởng!'
        },
        {
            'meal_id': 5,
            'name': 'Gà tây "Trứng cuộn trong bát" với Mayo cay',
            'source': 'icons_and_images/Turkey Egg Roll in a Bowl with Spicy Mayo.png',
            'cookware': 'Dao;thớt;đồ khui hộp;ly đo lường;muỗng đong;âu trộn bột;chao;dụng cụ gọt rau củ;dụng cụ nghiền khoai tây;đồ đánh trứng;máy trộn salad;cái nạo;cái kéo;máy vắt trái cây;dụng cụ ép tỏi;dao gọt;dao cắt bánh mì;đồ mài dao;',
            'ingredients': '2 Cà- rốt;2 Quả trứng;4	Trái tỏi;2 trái( 2,5cm) Rễ gừng;1 núm nhỏ Hành lá;Nửa Kg Gà tây xay;1 Trái bắp cải;1 Hành vàng( độ lớn trung bình);nước sốt ớt tỏi;ớt đỏ nghiền nát;mayonnaise;muối;hạt mè;nước tương tamari;dầu mè nướng;',
            'cook': '1. Làm nóng chảo lớn trên lửa vừa và cao.;2.Rửa và làm khô các sản phẩm tươi.(2 (2,5cm) củ gừng,2 củ cà rốt vừa,1 bắp cải napa đầu vừa,1 bó nhỏ hành lá (hành lá));3.Sau khi chảo nóng, thêm dầu và xoáy để tráng phần đáy. Cho 2 thìa dầu mè nướng;4.Thêm gà tây xay vào chảo, nấu, dùng thìa bẻ đôi cho đến khi gần chín, 3-4 phút.(Bỏ vào 690gram gà tây xay);5.Bóc vỏ và băm nhuyễn tỏi. Hành tây bỏ vỏ, thái hạt lựu nhỏ. Thêm cả hai vào chảo.(4 tép tỏi,1 củ hành tây vàng vừa);6.Gọt vỏ và băm hoặc cạo gừng. Cho gà tây vào chảo và xào trong 30 giây.;7.Gọt vỏ cà rốt và cắt bỏ phần cuối, sau đó bào sợi hoặc bào sợi thô. Thêm vào chảo.;8.Cắt bỏ phần cuối gốc của bắp cải, cắt đôi bắp cải theo chiều dọc, sau đó cắt lát mỏng theo chiều ngang thành các sợi nhỏ và cho vào chảo.;9.Nêm rau và gà tây với nước tương và ớt đỏ nghiền, khuấy để kết hợp. Nấu, thỉnh thoảng đảo đều, cho đến khi bắp cải và cà rốt mềm, 4-5 phút.(¼ chén nước tương Tam Thái Tử,⅛ muỗng cà phê ớt đỏ nghiền);10.Trong khi đó, cắt bỏ đầu hành lá, cắt hành tây theo chiều ngang thành các miếng 2,5cm ở một góc, để sang một bên.;11.Khi bắp cải đã chín, chắt hết chất lỏng dư thừa ra ngoài và vặn lửa nhỏ lại. Tạo một cái giếng ở giữa chảo và đập trứng vào đó. Đảo đều cho đến khi không còn chảy nước, 1-2 phút, sau đó khuấy đều để kết hợp.(Cho 2 quả trứng);12.Trong một bát nhỏ, trộn nước mắm tỏi ớt, muối và mayo với nhau.(2 muỗng cà phê nước sốt ớt tỏi, ⅛ muỗng cà phê muối,¼ chén mayonnaise);13.Để phục vụ hỗn hợp cuộn trứng chia giữa các bát, trên cùng là hành lá, hạt vừng và sốt mayo cay. Tận hưởng món ăn!(2 muỗng canh hạt mè);'
        }
    ]




    breakfast = [
        {
            'meal_id': 6,
            'name': 'Bữa sáng kiểu Ba Tư bánh mì dẹt với sữa chua, nấm bào ngư & thảo mộc tươi',
            'source': 'icons_and_images/Persian Breakfast Flatbread with Yogurt, Feta & Fresh Herbs.png',
            'cookware': 'dao;chao;thớt;máy ép tỏi(tùy chọn); chảo nướng; ly đo lường; muỗng đong;âu trộn bột;thìa khuấy;kẹp;máy gọt rau củ',
            'ingredients': '110gram pho mát feta vụn;1 dưa chuột Anh;2 bánh mì dẹt;1 nửa gói bạc hà tươi nhỏ;1 cây đinh đinh hương;tỏi;1 bó nhỏ ngò tây Ý(lá dẹt);2 tách sữa chua Hy Lạp;2 quả cà chua;tiêu đen;dầu ô liêu nguyên chất;muối;',
            'cook': '1.Rửa và làm khô các sản phẩm tươi.(2 quả cà chua,1 quả dưa chuột kiểu Anh,½ gói bạc hà tươi,½ bó nhỏ mùi tây Ý (lá dẹt));2.Cắt mỏng cà chua, chuyển sang một tấm.;3.Gọt vỏ dưa chuột, sau đó cắt bỏ đầu và bỏ đi. Thái nhỏ dưa chuột vừa và cho vào đĩa cùng với cà chua.;4.Cạo lá mùi tây bỏ cuống, Loại bỏ phần thân và phần lá. Chuyển sang một cái bát nhỏ.;5.Làm nóng chảo nướng hoặc chảo thông thường trên lửa vừa và cao.;6.Nhặt lá bạc hà khỏi thân, Loại bỏ phần thân và phần lá. Cho rau mùi tây vào bát.;7.Làm theo từng mẻ nếu cần, cho bánh mì dẹt vào chảo nướng nóng và nấu, lật giữa chừng, cho đến khi nướng nhẹ, khoảng 5 phút cho mỗi bánh mì dẹt.(2 bánh mì dẹt);8.Bóc vỏ và băm nhuyễn tỏi.(1 tép tỏi);9.Cho tỏi và sữa chua vào bát vừa và khuấy đều. Múc sữa chua dẻo lên trên bánh mì dẹt ấm.(2 cốc sữa chua Hy Lạp nguyên chất);10.Phủ lên trên bánh mì dẹt với cà chua, dưa chuột, feta, rau thơm và một ít dầu, nêm muối và tiêu.(110gram pho mát Feta vụn,2 muỗng canh dầu ô liu nguyên chất,⅛ muỗng cà phê muối,⅛ muỗng cà phê tiêu đen);11.Cắt bánh mì dẹt thành hình nêm và chia giữa các đĩa. Tận hưởng món ăn thôi!'
        },
        {
            'meal_id': 7,
            'name': 'Cháo Bữa sáng Keto Ricotta',
            'source': 'icons_and_images/Keto Ricotta Breakfast Porridge.png',
            'cookware': 'dao;thớt;ly đo lường;muỗng đong;chảo vừa;thìa khuấy',
            'ingredients': '110gram kem tươi; ¼ cốc hạt hồ đào;425gram phô mai ri-cô-ta;bơ, không ướp muối;quế;',
            'cook': '1.Đun nóng chảo ở lửa vừa.;2.Đun chảy bơ trong chảo.(½ chén bơ, không ướp muối);3.Thêm quế và kem và nấu, thỉnh thoảng khuấy cho đến khi kem ấm.(½ muỗng cà phê quế,4 fl oz (½ cốc) kem nặng);4.Lấy ra khỏi và khuấy với phô mai ricotta.(425gram pho mát ricotta);5.Cắt nhỏ quả hồ đào.(¼ cốc hồ đào, rang khô);6.Để phục vụ, chuyển sang bát và rắc quế và hồ đào.(⅛ muỗng cà phê quế)'
        },
        {
            'meal_id': 8,
            'name': 'Trứng cuộn, rau chân vịt và phô mai Parmesan',
            'source': 'icons_and_images/Scrambled Egg, Spinach & Parmesan Breakfast Wrap.png',
            'cookware': 'chao;bàn mài;muỗng đong;âu trộn bột;chảo chống dính;dao bay;đồ đánh trứng hoặc nĩa',
            'ingredients': '140gram rau chân vịt;8 quả trứng;bột mì tortilla;55gram phô mai Parmesan;tiêu đen; bơ, không ướp muối; ớt đỏ nghiền nát;muối;',
            'cook': '1.Rửa và lau khô rau chân vịt (bỏ qua bước này nếu rau chân vịt đã được rửa sạch trước).(140gram rau chân vịt non);2.Làm nóng chảo trên lửa vừa.;3.Đập trứng vào bát vừa và thêm gia vị, đánh đều.(8 quả trứng,1 muỗng cà phê muối,½ muỗng cà phê tiêu đen,½ muỗng cà phê ớt đỏ nghiền);4.Sau khi chảo nóng, thêm bơ và xoáy để phủ dưới đáy, Thêm rau chân vịt và nấu, đảo liên tục, cho đến khi héo, 1-2 phút.(2 muỗng canh bơ, không ướp muối);5.Đổ hỗn hợp trứng vào chảo. Đánh trứng bằng cách sử dụng kết hợp khuấy và lật, đảm bảo trộn đều hỗn hợp từ các cạnh của chảo. Nấu cho đến khi trứng không còn chảy nước.;6.Nghiền mịn phô mai Parmesan.(Phô mai Parmesan 55gram);7.Tháo chảo ra khỏi bếp. Rắc trứng với phô mai Parmesan, khuấy để kết hợp.;8.Đặt bánh ngô lên một mặt phẳng và phủ hỗn hợp trứng lên trên. Cuộn chặt chẽ để đóng lại. Tận hưởng món ăn!(bột mì tortilla);'
        },
        {
            'meal_id': 9,
            'name': 'Bữa sáng bít tết & trứng cổ điển với bơ và cà chua',
            'source': 'icons_and_images/Classic Steak & Eggs Breakfast with Avocado and Tomato.png',
            'cookware': 'giấy bạc;cái thìa;chảo thép không gỉ hoặc gang;kẹp',
            'ingredients': '1 quả bơ;8 quả trứng;0,45kg bít tết thăn lưng (dải New York);1 quả cà chuatiêu;đen;dầu ô liu nguyên chất;muối;',
            'cook': '1.Rửa và làm khô các sản phẩm tươi: 1 quả bơ, 1 quả cà chua;2.Cắt đôi và cắt lát mỏng cà chua thành một nửa, để qua một bên.;3.Cắt đôi quả bơ, cắt lát chéo khi vẫn còn vỏ và dùng thìa xúc ra, để qua một bên.;;4.Làm nóng chảo lớn trên lửa vừa và cao.5.Dùng khăn giấy thấm khô miếng bít tết và đặt lên đĩa, nêm muối và tiêu cho cả hai mặt.(Bít tết thăn lưng 1 lb (dải New York),½ muỗng cà phê muối,½ muỗng cà phê tiêu đen);6.Sau khi chảo nóng, thêm dầu và xoáy để tráng phần đáy. Thêm bít tết và nấu cho đến khi chín như mong muốn, 2-5 phút mỗi bên. Chuyển sang đĩa và đậy kín bằng giấy bạc.(1 muỗng cà phê dầu ô liu nguyên chất);7.Chuyển chảo về mức cao vừa phải, đổ thêm dầu và xoáy để tráng phần đáy. (2 muỗng cà phê dầu ô liu nguyên chất);8.Làm theo từng mẻ nếu cần, nhẹ nhàng cho trứng vào chảo và nêm muối và tiêu. Nấu cho đến khi phần lòng trắng se lại nhưng lòng đỏ vẫn chảy nước, khoảng 3-4 phút. (8 quả trứng, ¼ muỗng cà phê muối, ¼ muỗng cà phê tiêu đen);9.Trong khi đó, cắt lát mỏng miếng bít tết so với hạt.;10.Để phục vụ, chia bít tết và trứng giữa các đĩa. Trang trí với cà chua và bơ. Hưởng thức'
        },
        {
            'meal_id': 10,
            'name': 'Pizza thịt xông khói, cà chua & phô mai Mozzarella',
            'source': 'icons_and_images/Bacon, Tomato & Mozzarella Breakfast Pizza.png',
            'cookware': 'Khay đựng thức ăn;Dao làm bếp;Cái thớt;Dụng cụ nạo; Muốn đo dung tích;Găng tay cách nhiệt;Muỗn có rãnh;Vét bột;Cái chảo',
            'ingredients': '4 miến thịt lợn hun khói;4 quả trứng gà;4 ổ bánh mì dẹt;227g Phô mai mozzarella;2 trái cà chua ;Tiêu đen và muối;',
            'cook': '1.Làm nóng lò ở 220 ° C;2.Làm nóng chảo trên lửa vừa và cao.;3.Chặt thịt ba chỉ thành từng miếng vừa ăn. Thêm vào chảo và nấu cho đến khi giòn, 3-4 phút. Khi hoàn thành, dùng thìa có rãnh để chuyển thịt xông khói ra đĩa có lót khăn giấy và lau khô.(4 lát thịt xông khói);4.Rửa sạch, lau khô và cắt lát cà chua.(Cho 2 quả cà chua);5.Bào pho mai.(227 g phô mai mozzarella khối);6.Đặt bánh mì phẳng trên khay nướng; xếp cà chua, pho mát và thịt xông khói trên bánh mì dẹt, để trứng ở giữa.(Sau đó thêm 4 bánh mì dẹt);7.Nhẹ nhàng đập một quả trứng vào giữa mỗi chiếc bánh mì dẹt. Nướng cho đến khi trứng se lại, khoảng 8 phút.(Cần đập 4 quả trứng);8. Để phục vụ, chuyển pizza ra đĩa và nêm muối và tiêu.Tận hưởng món ăn!(125g muỗng cà phê muối,125g muỗng cà phê tiêu đen)'
        }
    ]




    lunch = [
        {
            'meal_id': 11,
            'name': 'Salad mì châu Á với xà lách trộn bông cải xanh và sốt kem đậu phộng',
            'source': 'icons_and_images/Asian Noodle Salad with Broccoli Slaw & Creamy Peanut Sauce.png',
            'cookware': 'Dao;chao;thớt;máy ép tỏi(tùy chọn);nồi lớn;ly đo lường;muỗng đong;âu trộn bột;rổ quay rau(tùy chọn);thìa khuấy;kẹp;đồ đánh trứng hoặc nĩa',
            'ingredients': '340g bông cải xanh; 1 bó nhỏ ngò; 2 tép tỏi; 340 g mì ống spaghetti không chứa gluten;1 quả chanh; ½ cốc đậu phộng rang không muối; ớt đỏ nghiền nát;mật ong;bơ đậu phộng tự nhiên;gạo giấm;muối; nước tương tamari;dầu mè nướng;',
            'cook': '1.Đổ nước vào 1 nửa nồi, đậy nắp và đun sôi. Mở nắp ra, thêm muối và mì ống, và khuấy trong vài giây. Nấu cho đến khi có độ cứng mong muốn, 8 - 10 phút.(khoảng 14 cốc nước,2 muỗng canh muối,340 g (1 phần tư xu = 56 g) mì ống spaghetti không chứa gluten);2.Bóc vỏ và băm nhuyễn tỏi. Trong một bát vừa, chuẩn bị nước sốt bằng cách trộn đều tỏi, nước, bơ đậu phộng, giấm, xì dầu, mật ong, dầu và hạt tiêu.(2 tép tỏi,4 muỗng canh nước ấm,8 muỗng canh bơ đậu phộng tự nhiên,2 muỗng canh giấm gạo,2 muỗng canh nước tương không chứa gluten,1 muỗng canh mật ong,1 muỗng canh dầu mè nướng,¼ muỗng cà phê ớt đỏ nghiền);3.Để bông cải xanh vào một cái bát lớn. Ngò rí rửa sạch và lau khô. Cạo lá khỏi thân, Loại bỏ thân và băm nhuyễn lá. Thêm vào bát.(1 (340 g) pkg súp lơ xanh,1 bó nhỏ ngò);4.Rửa sạch và cắt miếng chanh vừa ăn. Băm nhỏ đậu phộng.(1 vôi,½ chén đậu phộng rang không muối)5.Xả mì ống trong chao và rửa sạch dưới vòi nước lạnh. Lắc để xả hết chất lỏng dư thừa, sau đó cho vào bát có cối nghiền bông cải xanh.;6.Đổ nước sốt đậu phộng lên trên và phủ đều.;7.Để phục vụ, cho mì vào tô và trang trí với đậu phộng và chanh. Tận hưởng món ăn!'
        },
        {
            'meal_id': 12,
            'name': 'Mỳ Ý & Thịt viên Cổ điển với Sốt cà chua',
            'source': 'icons_and_images/Classic Spaghetti & Meatballs with Tomato Sauce.png',
            'cookware': 'Đồ khui hộp;dao;chao;thớt;máy ép tỏi(tùy chọn);bàn mài;ly đo lường;muỗng đong;chảo vừa;âu trộn bột;chảo bằng thép không gỉ;thìa khuấy;kẹp',
            'ingredients': '142gram rau chân vịt; 1 lon (398 ml) cà chua thái hạt lựu; 4 tép tỏi; 1 bó nhỏ Ngò tây Ý (lá dẹt); 0,68 kg thịt bò nạc xay; 28 g phô mai Parmesan; 284 g mì spaghetti; 2 lon (213 ml) nước sốt cà chua; 1 củ hành vàng vừa;tiêu đen;ớt đỏ nghiền nát;dầu ô liu nguyên chất;bánh mì panko;muối;',
            'cook': '1.Cho nước vào nồi, đậy nắp và đun sôi.;2.Rửa và làm khô các sản phẩm tươi.(1 (142 g) pkg rau bina non,1 bó nhỏ mùi tây Ý (lá dẹt));3.Cạo lá mùi tây khỏi thân, Loại bỏ thân và băm nhuyễn lá. Chuyển một nửa mùi tây vào bát vừa và nửa còn lại vào bát nhỏ.;4.Bóc vỏ và băm nhuyễn hành tây.(1 củ hành tây vàng vừa);5.Bóc vỏ và băm nhuyễn tỏi, Chuyển một nửa số hành và tỏi vào bát vừa với rau mùi tây và nửa còn lại vào một bát nhỏ khác.(4 tép tỏi);6.Cho thịt bò xay, vụn bánh mì và gia vị vào tô vừa với hỗn hợp rau mùi tây, hành tây và tỏi. Trộn bằng tay của bạn cho đến khi hỗn hợp trộn đều.(0,68 kg thịt bò nạc xay,¼ cốc vụn bánh mì panko,½ muỗng cà phê muối,½ muỗng cà phê tiêu đen,1 muỗng cà phê gia vị Ý,¼ muỗng cà phê ớt đỏ nghiền);7.Làm nóng chảo lớn ở lửa vừa.;8.Dùng một muỗng canh, nặn hỗn hợp thịt thành những viên tròn.;9.Thêm dầu ô liu vào chảo và đảo đều để tráng đáy.(1 muỗng canh dầu ô liu nguyên chất);10.Khi nước sôi, nêm muối và cho mì ống vào. Nấu mì cho đến khi có độ cứng mong muốn, từ 8 đến 10 phút. Sau khi hoàn thành, để ráo trong chao.(2 muỗng canh muối,284 g (1 phần tư xu = 57 g) mì ống spaghetti);11.Cho thịt viên vào chảo và nấu, thỉnh thoảng đảo đều cho đến khi chúng chín vàng ở tất cả các mặt và gần như chín trong tổng thời gian từ 4 đến 5 phút. Sau khi hoàn thành, chuyển sang bát hoặc đĩa. Nấu theo mẻ nếu cần thiết.;12.Sau khi đã chuyển thịt viên, cho thêm dầu ô liu vào chảo, tiếp theo cho phần hành và tỏi còn lại vào. Nấu và khuấy thường xuyên, cho đến khi hành tây mềm, 3 đến 4 phút.(1 muỗng canh dầu ô liu nguyên chất);13.Cho cà chua thái hạt lựu, nước sốt cà chua và gia vị vào chảo. Cho thịt viên trở lại chảo, giảm lửa ở mức vừa - nhỏ và nấu cho đến khi thịt viên chín và nước sốt hơi sệt lại, từ 6 đến 8 phút.(1 (398 ml) cà chua thái hạt lựu,1 lon nước sốt cà chua (213 ml),½ muỗng cà phê muối,½ muỗng cà phê tiêu đen,1 muỗng cà phê gia vị Ý);14.Xay nhuyễn ½ cốc Parmesan.(28 g phô mai Parmesan);15.Thêm rau chân vịt vào nước sốt và gấp lại cho đến khi nó héo. Lấy chảo ra khỏi bếp.;16.Để phục vụ, chia mì ống ra giữa các bát, múc nước sốt và thịt viên lên trên, rắc phần ngò tây còn lại và Parmesan bào. Tận hưởng món ăn!'
        },
        {
            'meal_id': 13,
            'name': 'Bò Hawaii & ớt dứa với rau chân vịt & bơ',
            'source': 'icons_and_images/Hawaiian Beef & Pineapple Chili with Spinach & Avocado.png',
            'cookware': 'Đồ khui hộp;dao;chao;thớt;máy ép tỏi(tùy chọn);muỗng đong;chảo vừa;âu trộn bột;thìa khuấy',
            'ingredients': '2 trái bơ;142g ray chân vịt;2 lon(398ml) cà chua thái hạt lựu;4 tép tỏi;0,68 kg thịt bò nạc xay;1 trái dứa nhỏ;1  củ hành đỏ;tiêu đen;bột ớt;thì là;Muối;',
            'cook': '1.Rửa và làm khô các sản phẩm tươi. (Bỏ qua rau chân vịt nếu nó đã được rửa trước.)(1 quả dứa nhỏ,2 quả bơ,1 (142 g) pkg rau bina non);2.Bóc vỏ và thái hạt lựu nhỏ hành tây, chuyển sang một cái bát nhỏ.(1 củ hành tím vừa);3.Bóc vỏ và băm nhuyễn tỏi, cho vào bát hành phi.(4 tép tỏi);4.Cắt bỏ vỏ của dứa, cắt đôi hoặc 1/4 theo chiều dài của quả dứa rồi cắt bỏ phần lõi. Cắt thịt thành từng miếng vừa ăn và chuyển sang bát vừa.;5.Đun nóng chảo trên lửa vừa-to.;6.Cho hành tây và thịt bò xay vào nồi, Nấu chín, bẻ thịt thành từng miếng nhỏ hơn, cho đến khi thịt bò chín vàng và hành tây chín mềm, khoảng 3 đến 5 phút.(0,68 kg thịt bò nạc xay);7.Nêm thịt bò với ớt bột, thìa là, muối, tiêu, khuấy cho đến khi có mùi thơm, 15 đến 30 giây.(2 muỗng canh ớt bột,1 thìa cà phê thìa là,1 muỗng cà phê muối,1 muỗng cà phê tiêu đen);8.Cho gần như tất cả dứa (để dành một vài miếng để trang trí) và cà chua thái hạt lựu vào nồi, khuấy để trộn.(2 lon (398 ml) cà chua thái hạt lựu);9.Tăng lửa và đun sôi ớt. Khi sôi, giảm lửa nhỏ, đậy nắp và nấu trong 10 phút.;10.Cắt nửa quả bơ, Vớt thịt và bỏ da. Cắt nhỏ thịt và chuyển sang một cái bát nhỏ.;11.Cho rau muống vào xào cùng ớt cho đến khi héo.;12.Chia ớt cho bốn bát (hoặc hai bát và hai hộp đựng đồ ăn trưa) và trang trí với các miếng dứa và bơ còn lại. Tận hưởng món ăn!'
        },
        {
            'meal_id': 14,
            'name': 'Pumpkin Mac & Cheese',
            'source': 'icons_and_images/Brown Butter Pumpkin Mac & Cheese.png',
            'cookware': 'Đồ khui hộp;chao;bàn mài;nồi lớn;ly đo lường;muỗng đong;chảo vừa;thìa khuấy;đồ đánh trứng hoặc nĩa',
            'ingredients': '227 g phô mai cheddar;½ gói nhỏ cỏ xạ hương tươi;340 g mì ống macaroni (cùi chỏ);½ (398 ml) lon bột bí ngô nguyên chất;296 ml sữa nguyên chất;bột mì;tiêu đen;bơ, không ướp muối;Muối;',
            'cook': '1.Đổ nước vào nửa nồi, đậy nắp và đun sôi. Mở nắp, thêm mì ống và muối, và khuấy trong vài giây. Nấu cho đến khi có độ cứng mong muốn, 8 - 10 phút.(340 g mì ống macaroni (cùi chỏ),2 muỗng cà phê muối);2.Trong khi mì đang nấu, đun chảy bơ trong chảo vừa với lửa vừa và cao. Khuấy đều, nấu cho đến khi bơ chuyển sang màu nâu, 3-4 phút. Cẩn thận để nó không bị cháy.(2 muỗng canh bơ, không ướp muối);3.Lấy chảo ra khỏi bếp, cho bột mì vào khuấy đều, liên tục 1 phút.(2 muỗng canh bột mì đa dụng);4.Đun nóng chảo trở lại, cho sữa vào khuấy dần. Đun nhỏ lửa và nấu trong 1 phút, khuấy liên tục cho đến khi đặc.(296 ml sữa nguyên chất);5.Rửa và lau khô cỏ xạ hương. Trượt lá khỏi thân cây; loại bỏ thân cây.(½ gói cỏ xạ hương tươi);6.Cho bí đỏ, muối, tiêu và hầu hết cỏ xạ hương vào xào cùng (để riêng một ít để trang trí).(½ (398 ml) có thể xay nhuyễn bí ngô,1 muỗng cà phê muối,¼ muỗng cà phê tiêu đen);7.Bào pho mát và cho vào chảo. Thỉnh thoảng vừa đun vừa khuấy cho đến khi phô mai tan chảy.(1 khối (227 g) phô mai cheddar);8.Khi mì ống đã nấu xong, để ráo nước trong chao và trở lại nồi. Thêm nước sốt phô mai vào nồi và khuấy đều.;9.Để phục vụ, chia mì ống và pho mát giữa các đĩa hoặc bát và rắc cỏ xạ hương tươi. Tận hưởng món ăn!'
        },
        {
            'meal_id': 15,
            'name': 'Rau & Hạt điều xào với cơm Basmati',
            'source': 'icons_and_images/Vegetable & Cashew Stir Fry with Basmati Rice.png',
            'cookware': 'Dao;chao;thớt;máy ép tỏi(tùy chọn);bàn mài(tùy chọn);ly đo lường;muỗng đong;âu trộn bột;chảo nhỏ;chảo thép không gỉ;thìa khuấy;máy gọt rau củ;đồ đánh trứng hoặc nĩa',
            'ingredients': '1 ly Gạo basmati;2 chùm bông cải xanh;1 ly hạt điều rang muối;2 tép tỏi;2 miếng (2 ½ cm) gừng;2 ớt chuông đỏ;2 gói(227 g) đậu Hà Lan;bột ngô;ớt đỏ nghiền nát;Muối;xì dầu;dầu dừa tinh khiết;',
            'cook': '1.Dùng rây lọc hoặc chao, vo gạo dưới vòi nước lạnh, sau đó để ráo và chuyển sang một cái chảo nhỏ. Nêm gạo với muối và thêm nước, Đun sôi hỗn hợp trên lửa lớn.(1 chén cơm basmati,¼ muỗng cà phê muối,473 ml (2 cốc) nước);2.Rửa sạch bông cải xanh, ớt chuông và đậu Hà Lan ngâm đường.(2 vương miện bông cải xanh,2 quả ớt chuông đỏ,2 (227 g) pkg đậu Hà Lan ngâm đường);3.Khi chất lỏng sôi, khuấy đều hỗn hợp, đậy vung và giảm lửa nhỏ. Nấu cơm cho đến khi chất lỏng ngấm hoàn toàn, từ 15 đến 18 phút. Sau khi hoàn thành, lấy cơm ra khỏi bếp và để yên trong 5 phút.;4.Tách bông cải xanh thành những bông hoa vừa ăn, cắt cọng thành những miếng nhỏ hơn, cho vào tô lớn. Bỏ hạt, thái hạt lựu vừa và cho ớt chuông vào bát. Cắt một nửa đậu Hà Lan và cho vào bát.;5.Đun nóng chảo trên lửa vừa-cao.;6.Bóc vỏ và băm nhuyễn tỏi. Gọt vỏ và băm hoặc cạo gừng.(2 tép tỏi,2 (2 ½ cm) củ gừng);7.Trong một bát nhỏ, chuẩn bị nước sốt bằng cách đánh đều nước tương và bột ngô.(4 muỗng canh nước tương,2 muỗng cà phê bột bắp);8.Phủ dầu lên đáy chảo. Thêm tỏi, gừng và ớt đỏ đã đập dập. Nấu cho đến khi có mùi thơm, 15-30 giây.(2 muỗng canh dầu dừa nguyên chất,¼ muỗng cà phê ớt đỏ nghiền);9.Cho tất cả các loại rau từ bát vào chảo. Xào cho đến khi chín mềm trong 4-5 phút.;10.Thêm nước sốt và hạt điều vào chảo. Xào cho đến khi rau và hạt điều phủ đều với nước sốt, 1-2 phút.(1 cốc hạt điều rang muối);11.Dùng nĩa để lật cơm.;12.Cho cơm vào bát và lên trên cùng với món xào. Tận hưởng món ăn!'
        }
    ]




    dessert = [
        {
            'meal_id': 16,
            'name': 'Sinh tố sô cô la hạnh nhân kem chuối & bơ',
            'source': 'icons_and_images/Creamy Chocolate Almond Smoothie with Banana & Avocado.png',
            'cookware': 'Dao;thớt; máy xay sinh tố cầm tay hoặc thông thường;ly đo lường;muỗng đong',
            'ingredients': '710 ml sữa hạnh nhân không đường;1 trái bơ;6 chuối;quế;bột ca cao;bơ hạnh nhân tự nhiên;xi-rô cây phong nguyên chất;Muối;',
            'cook': '1.Công thức này sẽ làm được khoảng 8 cốc. Làm việc theo lô để phù hợp nhất với máy xay của bạn.;2.Chuối lột vỏ, bẻ thành từng khoanh và cho vào máy xay sinh tố.(6 quả chuối);3.Rửa sạch, cắt đôi và cắt nhỏ quả bơ, thêm vào máy xay sinh tố.(1 quả bơ);4.Cho bơ hạnh nhân, bột ca cao, sữa hạnh nhân, xi-rô cây phong, quế, muối và 8 viên đá vào máy xay.(½ chén bơ hạnh nhân tự nhiên,¼ cốc bột cacao,710 ml sữa hạnh nhân, không đường,2 muỗng cà phê xi-rô cây phong nguyên chất,½ muỗng cà phê quế,⅛ muỗng cà phê muối);5.Xay ở tốc độ cao trong vài phút cho đến khi hết.;6.Rót sinh tố ra ly và thưởng thức!'
        },
        {
            'meal_id': 17,
            'name': 'Bột yến mạch sô cô la-dâu tây với hạnh nhân cắt lát',
            'source': 'icons_and_images/Chocolate-Strawberry Oatmeal with Sliced Almonds.png',
            'cookware': 'Dao;chao;thớt;ly đo lường;muỗng đong;chảo vừa;thìa khuấy;đồ đánh trứng hoặc nĩa',
            'ingredients': '1 ly Hạnh nhân, thái lát;½ (454 g) gói dâu tây;473 ml sữa nguyên chất;bột ca cao;yến mạch, nấu ăn nhanh;xi-rô cây phong nguyên chất;Muối;',
            'cook': '1.Cho muối và nước vào nồi vừa, đậy nắp và đun sôi trên lửa lớn.(⅛ muỗng cà phê muối,3 ½ cốc nước);2.Sau khi đun sôi, thêm yến mạch, bột ca cao và xi-rô cây phong, đánh trứng để kết hợp. Đậy nắp và để lửa nhỏ, 3-5 phút hoặc cho đến khi yến mạch đạt được độ sệt mong muốn.(2 cốc yến mạch, nấu nhanh,¼ cốc bột cacao,3 muỗng canh xi-rô cây phong nguyên chất);3.Trong khi đó, rửa sạch, cắt nhỏ và cắt lát mỏng dâu tây.(½ (454 g) pkg dâu tây);4.Để phục vụ, chia yến mạch giữa các bát và trên cùng với dâu tây, hạnh nhân và sữa. Tận hưởng món ăn!(1 cốc hạnh nhân, cắt lát,473 ml sữa nguyên chất);'
        },
        {
            'meal_id': 18,
            'name': 'Sinh tố Pumpkin Spice với Chuối & Gừng tươi',
            'source': 'icons_and_images/Pumpkin Spice Smoothie with Banana & Fresh Ginger.png',
            'cookware': 'Đồ khui hộp; dao;thớt;bàn mài(tùy chọn); máy xay sinh tố cầm tay hoặc thông thường;ly đo lường;muỗng đong',
            'ingredients': '2 quả chuối;2 (2 ½ cm) miếng rễ gừng;2 lon (398 ml) bột bí ngô nguyên chất;710 ml sữa nguyên chất;thảo quả, thục địa;quế, đất;đinh hương, mặt đất;nhục đậu khấu, mặt đất;xi-rô cây phong nguyên chất;',
            'cook': '1.Công thức này sẽ làm được khoảng 8 cốc. Làm việc theo lô để phù hợp nhất với máy xay của bạn.;2.Gừng rửa sạch, lau khô, gọt vỏ và băm nhuyễn, cho vào máy xay.(2 (2 ½ cm) củ gừng);3.Chuối lột vỏ, bẻ thành từng khoanh rồi cho vào máy xay sinh tố.(2 quả chuối);4.Cho bột bí đỏ, sữa, xi-rô cây phong, gia vị và 8 viên đá vào máy xay.(2 (398 ml) lon bột bí ngô nguyên chất,710 ml sữa nguyên chất,¼ cốc xi-rô cây phong nguyên chất,2 muỗng cà phê quế, xay,1 muỗng cà phê nhục đậu khấu, xay,½ thìa cà phê bạch đậu khấu,½ muỗng cà phê đinh hương, xay);5.Xay ở tốc độ cao trong vài phút cho đến khi hết.;6.Rót sinh tố vào ly. Rắc quế lên trên và thưởng thức!(⅛ muỗng cà phê quế, xay)'
        },
        {
            'meal_id': 19,
            'name': 'Sinh tố lê bạc hà, xoài & chuối xanh',
            'source': 'icons_and_images/Minty Pear, Mango & Banana Green Smoothie.png',
            'cookware': 'Dao; máy ép trái cây có múi (tùy chọn);chao;thớt; máy xay sinh tố cầm tay hoặc thông thường;ly đo lường; muỗng đong',
            'ingredients': '1 (142 g) gói Rau chân vịt non;2 quả chuối;1 ½ cốc edamame;1 Dưa chuột Anh;1 gói nhỏ bạc hà tươi;1 ly xoài đông lạnh;1 chanh;2 Quả Lê;xi-rô cây phong nguyên chất;',
            'cook': '1.Công thức này sẽ làm được khoảng 8 cốc. Làm việc theo lô để phù hợp nhất với máy xay của bạn.;2.Rửa và làm khô các sản phẩm tươi. (Bỏ rau chân vịt nếu nó đã được rửa sạch trước).(1 quả dưa chuột Anh,2 quả lê,1 chanh,1 pkg bạc hà tươi,2 quả chuối,1 (142 g) gói rau chân vịt non);3.Cắt nhỏ dưa chuột, chuyển vào máy xay cùng với nước lạnh và xi-rô cây phong. Xay đến khi hết.(1 ly nước,2 muỗng canh xi-rô cây phong nguyên chất);4.Lõi và cắt nhỏ quả lê, thêm vào máy xay.;5.Cho nước cốt chanh vào máy xay.;6.Nhặt lá bạc hà khỏi thân, Loại bỏ phần thân và cho lá vào máy xay.;7.Bóc vỏ chuối, bẻ thành từng khoanh và cho vào máy xay cùng với rau chân vịt.;8.Cho 8 viên đá, đậu edamame và xoài vào máy xay. Xay ở tốc độ cao trong vài phút cho đến khi hết.(1 ½ chén edamame,1 cốc xoài đông lạnh);9.Rót sinh tố ra ly và thưởng thức!'
        }
    ]




    veta = [
        {
            'meal_id': 20,
            'name': 'Đậu hũ mè nướng với bông cải xanh, ớt đỏ, hành lá & cơm',
            'source': 'icons_and_images/Baked Sesame Tofu with Broccoli, Red Pepper, Green Onion & Rice.png',
            'cookware': 'Chảo nướng;dao;chao;thớt;ly đo lường;muỗng đong;chảo vừa;găng chống nóng;thìa khuấy',
            'ingredients': '1 (510 g) túi bông cải xanh;2 (340 g) gói đậu hũ siêu cứng;1 bó nhỏ hành lá (hành lá);1 ly gạo jasmine;2 ớt chuông đỏ;tiêu đen;Muối;Hạt mè;nước sốt xào;dầu mè nướng;',
            'cook': '1.Làm nóng lò ở 220 ° C.,2.Cắt đôi đậu phụ theo chiều dài. Kẹp đậu phụ giữa khăn sạch hoặc khăn giấy và đặt lên khay nướng. Đặt một cái thớt có vật nặng lên trên và đặt sang một bên để ép bớt nước thừa.(2 (340 g) gói đậu phụ cứng);3.Dùng rây lọc hoặc chao, vo gạo dưới vòi nước lạnh, sau đó để ráo và chuyển sang một chiếc chảo vừa. Thêm nước và đun sôi hỗn hợp trên lửa lớn.(1 chén cơm jasmine,2 cốc nước);4.Khi chất lỏng sôi, khuấy đều hỗn hợp, đậy nắp nồi và giảm lửa xuống thấp. Nấu cơm cho đến khi chất lỏng được hấp thụ hoàn toàn, 15-18 phút. Sau khi hoàn thành, lấy cơm ra khỏi bếp và để yên, vẫn đậy nắp trong 5 phút.;5.Trong khi đó, hành lá rửa sạch, lau khô, cắt đôi theo chiều dọc. Cắt các phần màu trắng và xanh lá cây nhạt thành các miếng 1 inch và chuyển sang một khay nướng lớn. Cắt mỏng những phần có màu xanh đậm và để riêng.(1 bó nhỏ hành lá (hành lá));6.Ớt chuông rửa sạch, lau khô, cắt nhỏ và bỏ hạt, cắt đôi theo chiều ngang, sau đó cắt thành các dải mỏng. Cho ớt chuông và bông cải xanh vào khay nướng cùng với hành lá.(2 quả ớt chuông đỏ,1 (510 g) bông cải xanh túi);7.Đậu phụ thái hạt lựu vừa và cho vào khay nướng.;8.Đổ rau và đậu hũ vào xào với nước sốt và dầu, sau đó nêm muối và tiêu. Khuấy đều để áo và dàn đều.(1 chén sốt xào,4 thìa dầu mè nướng,½ muỗng cà phê muối,¼ muỗng cà phê tiêu đen);9.Đặt tấm nướng vào lò nướng (không cần phải làm nóng hoàn toàn) và nướng, đảo giữa chừng, cho đến khi rau củ mềm và đậu phụ ấm qua, khoảng 15 phút. Lấy ra khỏi lò.;10.Để phục vụ, chia cơm, đậu phụ, rau và nước sốt giữa các đĩa. Rắc hành lá và vừng rang. Tận hưởng món ăn!(2 muỗng canh hạt mè);'
        },
        {
            'meal_id': 21,
            'name': 'Sandwich "Thịt viên" chay Ý với Mozzarella & Marinara Homemade',
            'source': 'icons_and_images/Italian Veggie Meatball Sandwich with Mozzarella & Homemade Marinara.png',
            'cookware': 'Đĩa nướng;chảo nướng;đồ khui hộp;dao;chao;thớt;máy ép tỏi(tùy chọn);bàn mài;máy xay sinh tố cầm tay hoặc thông thường;nồi lớn;ly đo lường;muỗng đong;âu trộn bột;găng chóng nóng;thìa khuấy;kẹp',
            'ingredients': '2 lon (398 ml) cà chua thái hạt lựu;2 trứng;4 tép tỏi;1 bó nhỏ Ngò tây Ý (lá dẹt);1 (227 g) khối Phô mai mozzarella;28 g phô mai Parmesan;2 hẹ;454 g mặt đất rau, dựa trên thực vật;4 bánh hoặc cuộn ngũ cốc nguyên hạt;tiêu đen;đường nâu;ớt đỏ nghiền nát;dầu ô liu nguyên chất;gia vị của Ý;miếng bánh mì panko;Muối;',
            'cook': '1.Làm nóng lò ở 205 ° C.,2.Rửa sạch và lau khô mùi tây. Cạo lá khỏi thân, Loại bỏ thân và băm nhuyễn lá. Cho một nửa vào bát vừa, dành phần còn lại để trang trí.(1 bó nhỏ mùi tây Ý (lá dẹt));3.Bóc vỏ và băm nhuyễn hành tím và tỏi. Cho cả hai thứ vào bát cùng với mùi tây.(2 củ hẹ,2 tép tỏi);4.Cho rau xay, trứng, vụn bánh mì và gia vị vào tô. Trộn bằng tay của bạn cho đến khi kết hợp tốt.(454 g rau mài, gốc thực vật,2 quả trứng,½ chén vụn bánh mì panko,1 muỗng cà phê gia vị Ý,½ muỗng cà phê muối,½ muỗng cà phê tiêu đen);5.Phủ một lớp dầu mỏng lên đĩa nướng lớn. Dùng thước đo muỗng canh, nặn hỗn hợp thành những viên "thịt viên" tròn và xếp ra đĩa. Đặt món ăn vào lò nướng (không cần phải làm nóng hoàn toàn) và nướng cho đến khi chín trong khoảng 15 phút.(2 muỗng cà phê dầu ô liu nguyên chất);6.Trong khi đó, bóc vỏ tỏi và cho vào máy xay.(2 tép tỏi);7.Để ráo cà chua, cho vào máy xay cùng với đường và gia vị. Trộn trên cao cho đến khi gần như hết.(2 lon (398 ml) cà chua thái hạt lựu,2 muỗng cà phê đường nâu,1 muỗng cà phê gia vị Ý,½ muỗng cà phê muối,¼ muỗng cà phê tiêu đen);8.Cho dầu và nước nghiền cà chua vào một cái nồi lớn ở lửa vừa và nhỏ. Nấu và khuấy thường xuyên, cho đến khi nước sốt đặc và tỏi được nấu chín, 5-8 phút.(2 muỗng cà phê dầu ô liu nguyên chất);9.Trong khi đó, phô mai mozzarella bào mỏng, nghiền mịn Parmesan. Chuyển cả hai vào một bát vừa sạch và ném để kết hợp, để qua một bên.(1 (227 g) phô mai mozzarella khối,28 g phô mai Parmesan);10.Khi thịt viên đã hoàn thành, cẩn thận chuyển chúng vào nồi với nước sốt cà chua, khuấy để kết hợp.;11.Đặt lò nướng ở trên cao và đặt giá đỡ ở một phần ba phía trên của lò.;12.Chia đôi các cuộn và chuyển sang một khay nướng lớn, mặt cắt hướng lên trên. Đặt vào lò nướng và nướng cho đến khi nướng nhẹ, 1-2 phút. Lấy ra khỏi lò.(4 bánh hoặc cuộn ngũ cốc nguyên hạt);13.Đặt các phần trên của cuộn sang một bên, để lại phần dưới cùng trên tờ giấy nướng. Rắc một nửa phô mai lên dưới đáy cuộn. Chia thịt viên và nước sốt giữa các cuộn và phủ phô mai còn lại lên trên.;14.Cho khay nướng trở lại lò nướng và nướng cho đến khi phô mai chảy ra, khoảng 1 phút. Lấy ra khỏi lò.;15.Để phục vụ, rắc rau mùi tây và ớt đỏ nghiền nhỏ lên mỗi chiếc bánh sandwich. Đóng bánh mì và chia giữa các đĩa. Tận hưởng món ăn!(¼ muỗng cà phê ớt đỏ nghiền)'
        },
        {
            'meal_id': 22,
            'name': 'Món bibimbap cay kiểu súp lơ xào với rau củ & trứng',
            'source': 'icons_and_images/Spicy Bibimbap Style Cauliflower Stir-Fry with Veggie Ground & Eggs.png',
            'cookware': 'Dao;chao;thớt;máy ép tỏi(tùy chọn);bàn mài; máy vắt hoặc máy chế biến thực phẩm;âu trộn bột;chảo chống dính;chảo nhỏ;thìa;thìa khuấy;máy gọt rau củ;đồ đánh trứng hoặc nĩa',
            'ingredients': '1 (142 g) gói rau chân vịt non;2 củ cà rốt vừa;1 súp lơ trắng vừa;0,23 kg nấm cremini;4 trứng;4 tép tỏi;2 (2 ½ cm) miếng rễ gừng;1 bó nhỏ hành lá;4 muỗng canh tương cà chua;454 g Rau các loại(tùy chọn);ớt đỏ nghiền nát;xi-rô cây phong nguyên chất;gạo giấm;Hạt mè;xì dầu;dầu mè nướng;',
            'cook': '1.Cho trứng vào nồi nhỏ, đổ nước vào và đun sôi. Giảm lửa nhỏ và nấu trong 4 phút. Xả nước nóng và thêm đá hoặc chạy dưới vòi nước lạnh để làm mát.(4 quả trứng);2.Trong khi đó, rửa và làm khô các sản phẩm tươi sống. (Bỏ qua rau bina nếu nó đã được rửa trước.)(1 bông súp lơ trắng đầu vừa,0,23 kg nấm cremini,2 củ cà rốt vừa,1 (142 g) pkg rau chân vịt non,2 (2 ½ cm) củ gừng,1 bó nhỏ hành lá);3.Làm nóng chảo lớn trên lửa vừa và cao.;4.Sau khi chảo nóng, thêm dầu và xoáy để tráng phần đáy. Cho rau đã xay vào nấu chín, dùng thìa bẻ đôi cho đến khi chín vàng và vụn trong 3-4 phút. Lấy ra khỏi nhiệt, chuyển rau đã xay ra đĩa và để sang một bên. (Dự trữ chảo để sử dụng sau này.)(4 thìa dầu mè nướng,454 g rau mài, gốc thực vật);5.Trong khi đó, cắt đầu súp lơ thành các phần tư, sau đó tỉa bỏ bớt lá và phần thân dày. Sử dụng máy xay hộp hoặc máy xay thực phẩm, nạo nhỏ súp lơ và cho vào bát vừa.;6.Nấm cắt lát mỏng và cho vào tô cùng với súp lơ.;7.Gọt vỏ, cắt nhỏ và bào sợi cà rốt, thêm vào bát.;8.Chuyển chảo về nhiệt độ trung bình-cao, thêm dầu và xoáy để tráng phần đáy. Thêm rau và khuấy để kết hợp. (Dự trữ bát để sử dụng sau.)(4 thìa dầu mè nướng);9.Thêm một nắm rau bina vào chảo, đợi cho rau bina hơi héo trước khi thêm một nắm tiếp theo. Sau khi tất cả rau bina đã héo, dàn đều hỗn hợp rau và nấu, không khuấy, cho đến khi hình thành lớp vỏ nâu ở dưới cùng, khoảng 5 phút.;10.Trong khi đó, gọt vỏ và băm nhuyễn gừng và tỏi. Đặt cả hai vào bát đã đặt trước.(4 tép tỏi);11.Cắt nhỏ hành lá và cắt thành từng miếng mỏng. Cho gừng và tỏi vào bát.;12.Cho tương cà chua, giấm, dầu, xi-rô phong, nước tương, hạt mè và ớt đỏ nghiền vào bát. Đánh bông để kết hợp nước sốt.(4 muỗng canh tương cà chua,2 muỗng canh giấm gạo,2 muỗng canh dầu mè nướng,2 muỗng canh xi-rô cây phong nguyên chất,2 muỗng canh nước tương,1 muỗng cà phê hạt mè,½ muỗng cà phê ớt đỏ nghiền);13.Rưới nước sốt lên rau và khuấy đều. Đậy chảo và tiếp tục nấu, không bị xáo trộn, cho đến khi rau chín mềm, thêm 3-4 phút nữa.;14.Trả mặt đất rau vào chảo. Khuấy cho đến khi kết hợp và đun nóng trong 1-2 phút nữa. Loại bỏ khỏi nhiệt.;15.Trong khi đó, bóc vỏ và cắt đôi quả trứng.;16.Để phục vụ, chia món xào giữa các bát hoặc đĩa và trên cùng là trứng. Tận hưởng món ăn!'
        },
        {
            'meal_id': 23,
            'name': 'Cơm Burrito Súp Lơ Rau Ngò & Súp lơ',
            'source': 'icons_and_images/Cheesy Veggie Ground & Cilantro-Lime Cauliflower Rice Burrito Bowl.png',
            'cookware': 'Giấy bạc;dao;máy ép trái cây(tùy chọn);chao;thớt;máy ép tỏi(tùy chọn);bàn mài; máy vắt hoặc máy chế biến thực phẩm;muỗng đong;âu trộn bột;chảo chống dính;thìa khuấy',
            'ingredients': '1 trái bơ;1 súp lơ trắng vừa;½ (227 g) khối phô mai cheddar;1 bó nhỏ ngò;2 tép tỏi;1 gói nhỏ cà chua;2 chanh;454 g rau các loại(tự chọn);1 hành vàng;tiêu đen;bơ, không ướp muối;bột ớt;thì là;oregano, khô;Muối;',
            'cook': '1.Rửa và làm khô các sản phẩm tươi.(1 bông súp lơ trắng đầu vừa,1 bó nhỏ ngò,2 quả chanh,1 gói nhỏ cà chua,1 quả bơ);2.Làm nóng chảo lớn trên lửa vừa và cao.;3.Sau khi chảo nóng, thêm bơ và xoáy để phủ dưới đáy. Thêm rau và gia vị, nấu, dùng thìa bẻ đôi cho đến khi chín vàng và vụn, 3-4 phút.(4 muỗng cà phê bơ, không ướp muối,454 g rau các loại(tùy chọn),2 thìa cà phê thìa là, xay,2 muỗng cà phê ớt bột,1 muỗng cà phê oregano, khô,½ muỗng cà phê muối);4.Trong khi đó, bóc vỏ và băm nhuyễn tỏi. Sau khi xay rau xong, cho tỏi vào và khuấy đều. Chuyển sang bát vừa và đậy kín bằng giấy nhôm. (Dự trữ chảo để sử dụng sau này.)(2 tép tỏi);5.Hành tây bỏ vỏ, cắt đôi, thái hạt lựu nhỏ.(1 củ hành tây vàng vừa);6.Trở lại chảo ở nhiệt độ trung bình-cao, thêm nhiều bơ và xoáy để phủ dưới đáy. Thêm hành tây vào nấu, đảo thường xuyên cho đến khi hành tây bắt đầu mềm, khoảng 3-4 phút.(2 muỗng canh bơ, không ướp muối);7.Trong khi đó, cắt đầu súp lơ thành các phần tư, sau đó tỉa bỏ bớt lá và phần thân dày. Sử dụng máy xay hộp hoặc máy xay thực phẩm, nạo nhỏ súp lơ.;8.Cho súp lơ và gia vị vào chảo cùng với hành tây. Tiếp tục nấu, đảo thường xuyên, cho đến khi súp lơ vàng nhẹ và nấu chín, thêm 5-7 phút.(1 muỗng cà phê ớt bột,1 muỗng cà phê muối,½ muỗng cà phê tiêu đen);9.Trong khi súp lơ đang nấu, hãy bào mỏng phô mai.(½ (227 g) phô mai cheddar khối).;10.Ngò rí cạo bỏ cọng, Loại bỏ thân và băm nhỏ lá.;11.Cắt một miếng chanh thành các múi cau, dành phần vôi còn lại cho phần cơm súp lơ.;12.Khi cơm súp lơ đã hoàn thành, cho nước cốt chanh còn lại vào chảo. Thêm ngò và rau củ mài, khuấy nhẹ để kết hợp và tiếp tục nấu cho đến khi nóng qua, thêm 1-2 phút. Loại bỏ khỏi nhiệt.;13.Trong khi đó, cà chua giảm một nửa. Một nửa quả bơ và quả bơ, cắt lát mỏng khi vẫn còn nguyên vỏ, sau đó dùng thìa xúc ra.;14.Để phục vụ, chia hỗn hợp cơm súp lơ giữa các đĩa hoặc bát và trên cùng là pho mát bào, cà chua và bơTrang trí với chanh và thưởng thức!'
        },
        {
            'meal_id': 24,
            'name': 'Xúc xích chay Ý. Nướng với ớt, cà tím và hạt thông',
            'source': 'icons_and_images/Spicy Italian Veggie Sausage Bake with Peppers, Eggplant & Pine Nuts.png',
            'cookware': 'Chảo nướng;dao;chao;thớt;ly đo lường;muỗng đong;âu trộn bột;chảo chống dính;găng tay chống nống;thìa khuấy;kẹp',
            'ingredients': '2 cà tím;1 bó nhỏ ngò tây Ý (lá dẹt);½ cốc hạt thông;4 xúc xích thuần chay nấu sẵn;2 ớt chuông đỏ;2  hành tây đỏ vừa;2 ớt chuông vàng;tiêu đen;ớt đỏ nghiền nát;dầu ô liu nguyên chất;dấm rượu vang đỏ;Muối;',
            'cook': '1.Làm nóng lò ở 230 ° C  và đặt giá ở 1/3 trên của lò.;2.Rửa và làm khô các sản phẩm tươi.(2 quả ớt chuông đỏ,2 quả ớt chuông vàng,2 quả cà tím,1 bó nhỏ mùi tây Ý (lá dẹt));3.Cắt, bỏ hạt và cắt lát ớt chuông theo chiều dọc thành các dải mỏng. Chuyển sang một khay nướng lớn.;4.Cắt nhỏ và cắt hạt cà tím vừa. Cho ớt chuông vào khay nướng.;5.Bóc vỏ, cắt đôi và cắt lát hành tây theo chiều dọc thành các dải mỏng; thêm vào khay nướng.(2 củ hành tím vừa);6.Ướp rau với dầu và nêm gia vị, quăng để phủ và dàn đều một lớp.(¼ chén dầu ô liu nguyên chất,1 muỗng cà phê muối,½ muỗng cà phê tiêu đen,½ muỗng cà phê ớt đỏ nghiền);7.Đặt rau vào lò nướng (không cần phải làm nóng hoàn toàn) và nướng cho đến khi vừa mềm, khoảng 10 phút.;8.Trong khi đó, làm nóng chảo trên lửa vừa.;9.Khi chảo còn nóng, cho hạt thông vào. Nấu, khuấy liên tục, cho đến khi vàng nâu, 3-5 phút. Chuyển sang một bát nhỏ và đặt sang một bên.(½ chén hạt thông);10.Khi rau đã chín, lấy ra khỏi lò và đảo đều. Thêm xúc xích vào khay nướng, lồng chúng vào rau. Đổ thêm dầu vào xúc xích.(4 xúc xích thuần chay nấu sẵn,4 muỗng cà phê dầu ô liu nguyên chất);11.Đặt khay nướng trở lại lò và tiếp tục nướng cho đến khi xúc xích được làm ấm trong khoảng 5 phút.;12.Khi xúc xích được làm ấm qua, chuyển lò nướng sang nướng trên cao. Hầm cho đến khi rau và xúc xích chín vàng, khoảng 3 phút.;13.Trong khi đó, mùi tây cạo bỏ cuống, loại bỏ thân và cắt lá thô.;14.Lấy giấy nướng ra khỏi lò, thêm một nửa số rau mùi tây và giấm, sau đó trộn đều. (Dự trữ mùi tây còn lại để phục vụ.)(¼ cốc giấm rượu vang đỏ);15.Để phục vụ, chia xúc xích và rau giữa các đĩa. Trên cùng với hạt thông và mùi tây dành riêng. Tận hưởng!'
        }
    ]